Update OpenCV related Dockerfile and use NEON for OpenCV on Xavier NX

diff --git a/ROS-melodic-Xavier/Dockerfile.l4t.vins b/ROS-melodic-Xavier/Dockerfile.l4t.vins
--- a/ROS-melodic-Xavier/Dockerfile.l4t.vins
+++ b/ROS-melodic-Xavier/Dockerfile.l4t.vins
@@ -11,52 +11,30 @@ ENV DEBIAN_FRONTEND=noninteractive
 
 WORKDIR /opt
 
-RUN apt-get update && apt-get install -y --no-install-recommends \
-        software-properties-common \
-        apt-utils \
-        net-tools \
-        bash-completion \
-        python3-pip \
-        libcurl4-openssl-dev \
-        && rm -rf /var/lib/apt/lists/*
-
 ################################################################################################################################
 #
-# OpenCV
+# Install OpenCV from pkg
 #
-# remove prebuilt opencv
-RUN apt-get purge -y libopencv* python-opencv \
-    && apt-get update \
-    && apt-get install -y --no-install-recommends \
-    build-essential pkg-config file\
-    cmake libavcodec-dev libavformat-dev libavutil-dev \
-    libglew-dev libgtk2.0-dev libgtk-3-dev libjpeg-dev libpng-dev libpostproc-dev \
-    libswscale-dev libtbb-dev libtiff5-dev libv4l-dev libxvidcore-dev \
-    libx264-dev qt5-default zlib1g-dev libgl1 libglvnd-dev pkg-config \
-    libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev mesa-utils \
-    python2.7-dev python3-dev python-numpy python3-numpy \
-    && rm -rf /var/lib/apt/lists/*
 
-# OpenCV looks for the cuDNN version in cudnn_version.h, but it's been renamed to cudnn_version_v8.h
-RUN ln -s /usr/include/aarch64-linux-gnu/cudnn_version_v8.h /usr/include/aarch64-linux-gnu/cudnn_version.h
+# Remove previous OpenCV installation if it exists
+RUN apt purge -y '.*opencv.*' || echo "previous OpenCV installation not found"
 
-# references to related OpenCV compilation problems:
-# Ref1: https://forums.developer.nvidia.com/t/opencv-with-gl-support-at-xavier/76752
-# Ref2: https://forums.developer.nvidia.com/t/building-opencv-with-opengl-support/49741/17
-# WARNING: The following COPY won't work as /usr/local/cuda/ is actually a mounted volume from the host!
-# You will need to modify /usr/local/cuda/include/cuda_gl_interop.h on the HOST system
-# COPY ./packages/cuda_gl_interop.h /usr/local/cuda/include/
-# COPY ./packages/cuda_gl_interop.h /usr/local/cuda-10.2/include/
-RUN cd /usr/lib/aarch64-linux-gnu/ &&\
-    ln -sf libGL.so.1.0.0 libGL.so
+# Download and extract the deb packages
+ARG OPENCV_URL="https://github.com/ryrobotics/USR_Docker/raw/main/OpenCV/OpenCV-3.4.5-aarch64.tar.gz"
+ARG OPENCV_DEB="OpenCV-3.4.5-aarch64.tar.gz"
+RUN mkdir opencv && cd opencv \
+    && wget --quiet --show-progress --progress=bar:force:noscroll --no-check-certificate ${OPENCV_URL} -O ${OPENCV_DEB} \
+    && tar -xzvf ${OPENCV_DEB}
 
-# ARG OPENCV_VERSION="3.4.1"
-ARG OPENCV_VERSION="3.4.5"
-RUN git clone https://github.com/ryrobotics/USR_Docker /opt/USR_Docker &&\
-    cd /opt/USR_Docker/OpenCV &&\
-    tar -zxvf OpenCV-3.4.5-aarch64.tar.gz &&\
-    dpkg -i OpenCV*.deb &&\
-    rm -rf /opt/USR_Docker
+# Install the packages and their dependencies
+RUN cd opencv \
+    && dpkg -i --force-depends *.deb \
+    && apt update \
+    && apt install -y -f --no-install-recommends \
+    && dpkg -i *.deb \
+    && rm -rf /var/lib/apt/lists/* \
+    && rm -rf /opt/opencv \
+    && apt clean
 
 # Check opencv verison
 RUN pkg-config --modversion opencv
