Update for OpenCV

diff --git a/ROS-melodic-Xavier/Dockerfile.l4t.vins b/ROS-melodic-Xavier/Dockerfile.l4t.vins
--- a/ROS-melodic-Xavier/Dockerfile.l4t.vins
+++ b/ROS-melodic-Xavier/Dockerfile.l4t.vins
@@ -17,10 +17,10 @@ WORKDIR /opt
 #
 
 # Remove previous OpenCV installation if it exists
-RUN apt purge -y '.*opencv.*' || echo "previous OpenCV installation not found"
+RUN apt-get purge -y '.*opencv.*' || echo "previous OpenCV installation not found"
 
 # Download and extract the deb packages
-ARG OPENCV_URL="https://github.com/ryrobotics/USR_Docker/raw/main/OpenCV/OpenCV-3.4.5-aarch64.tar.gz"
+ARG OPENCV_URL="https://github.com/ryrobotics/USR_Docker/raw/OpenCV/OpenCV/OpenCV-3.4.5-aarch64.tar.gz"
 ARG OPENCV_DEB="OpenCV-3.4.5-aarch64.tar.gz"
 RUN mkdir opencv && cd opencv \
     && wget --quiet --show-progress --progress=bar:force:noscroll --no-check-certificate ${OPENCV_URL} -O ${OPENCV_DEB} \
@@ -29,12 +29,12 @@ RUN mkdir opencv && cd opencv \
 # Install the packages and their dependencies
 RUN cd opencv \
     && dpkg -i --force-depends *.deb \
-    && apt update \
-    && apt install -y -f --no-install-recommends \
+    && apt-get update \
+    && apt-get install -y -f --no-install-recommends \
     && dpkg -i *.deb \
     && rm -rf /var/lib/apt/lists/* \
     && rm -rf /opt/opencv \
-    && apt clean
+    && apt-get clean
 
 # Check opencv verison
 RUN pkg-config --modversion opencv
